[package]
name    = "gnat"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"


[dependencies.stm32l0xx-hal]
git      = "https://github.com/stm32-rs/stm32l0xx-hal.git"
features = [ "rt", "stm32l082" ]

[dev-dependencies]
cortex-m-rt = "0.6.10"
panic-halt  = "0.2.0"
