[package]
name    = "gnat"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"


[dependencies.stm32l0xx-hal]
version  = "0.2.0"
features = ["rt", "stm32l082"]

[dev-dependencies]
cortex-m    = "0.6.0"
cortex-m-rt = "0.6.10"
panic-halt  = "0.2.0"
usb-device  = "0.2.2"
usbd-serial = "0.1.0"

[dev-dependencies.stm32-usbd]
git      = "https://github.com/braun-embedded/stm32-usbd.git"
branch   = "stm32l0x2"
features = ["stm32l0x2xx"]


# Required because stm32-usbd depends on the latest crates.io version, while the
# examples in this repository depend on unreleased features.
[patch.crates-io.stm32l0xx-hal]
git = "https://github.com/stm32-rs/stm32l0xx-hal.git"


[profile.release]
incremental   = false
codegen-units = 1
lto           = true
opt-level     = "s"
